echo off
color 9
echo Fixing Disk 100%% Usage
echo ...
echo ...
echo ...
echo ...
echo ...
echo ...
echo ============================
echo ============================
ver

net.exe stop "Windows Search"
echo Done...
net.exe stop superfetch
echo Done...
net.exe stop sysmain
echo Done

echo Problem Fixed :)